#! /bin/sh
### BEGIN INIT INFO
# Provides: BeagleBoneMAIN.py
# Should-Start: console-screen dbus network-manager
# Required-Start: $remote_fs $network $local_fs
# Required-Stop: $remote_fs 
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: start myprogram at boot time
### END INIT INFO
#

####################
# /etc/init.d/erumby
####################
set -e

. /lib/lsb/init-functions

PATH=/bin:/usr/bin:/sbin:/usr/sbin:/usr/local/sbin:/home/debian/script

SCRIPT="/usr/local/sbin/erumbymain.sh"
PROGRAMNAME="BeagleBoneLED.py"
SCRIPT2="/usr/local/sbin/erumbyoff.sh"
case "$1" in
start)
     $SCRIPT
     ;;
stop)
     killall $PROGRAMNAME
     $SCRIPT2
     ;;
esac
